require("user.plugins.null_ls")
require("user.plugins.treesitter")
require("user.plugins.telescope")
require("user.plugins.lualine")
require("user.plugins.cmp")
require("user.plugins.snippy")
require("user.plugins.indent_blankline")
require("user.plugins.shade")
require('Comment').setup()
require("ufo").setup()
-- require("nvim-autopairs").setup()
